#!/bin/bash
prodDir=''
cp separate_ntp.C $prodDir
cd $prodDir
rm ntuples.list
ls *.root > ntuples.list
cat ntuples.list | while read line
do
root -l -q ./remove_ntp.C\(\"$line\"\)++
#root -l -q ../projectSignal.ine\"\)
#root -l -q ../projectBackground.C\(\"$line\"\)
done
rm res_ntp_all.root
hadd res_ntp_all.root res*
cp res_ntp_all.root ~/
