#!/bin/bash
cd rootFiles
rm ntuples.list
ls ntp* > ntuples.list
cat ntuples.list | while read line
do
root -l -q ../fit.cxx\(\"$line\"\)
root -l -q ../projectSignal.C\(\"$line\"\)
root -l -q ../projectBackground.C\(\"$line\"\)
done
rm res_ntp_all.root
hadd res_ntp_all.root res*
cp res_ntp_all.root ~/
