#!/usr/bin/env bash
#get_file_list.pl -cond trgsetupname=dAu200_production_2016,filename~st_physics,storage!=hpss -keys 'path,filename' -delim / -limit 0 > runs_path_test.txt
get_file_list.pl -cond trgsetupname=dAu200_production_2016,filename~st_physics,filetype~picoDst,storage=hpss -keys 'filename' -delim / -limit 0 > runs_filename_test.txt


