#!/bin/bash
prodDir='/gpfs01/star/pwg/lkramarik/Dmaker_dAu/workDir/2018-07-03_11-06/production/'
cp separate_ntp.C $prodDir
cd $prodDir
rm ntuples.list
ls *.root > ntuples.list
cat ntuples.list | while read line
do
root -l -q ./separate_ntp.C\(\"$line\"\)++
done
